// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDES9L5keG2HvOqHGyKad-sngmtCSAXNUo',
    appId: '1:268931083169:web:cb49083113214fcb9579e0',
    messagingSenderId: '268931083169',
    projectId: 'protocol-app-6fb88',
    authDomain: 'protocol-app-6fb88.firebaseapp.com',
    storageBucket: 'protocol-app-6fb88.firebasestorage.app',
    measurementId: 'G-ZG2X30B7CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoN32p-JbF4dmdzxiqARY-Pgj1Idzq5k',
    appId: '1:268931083169:android:5d134367bf4fd4ff9579e0',
    messagingSenderId: '268931083169',
    projectId: 'protocol-app-6fb88',
    storageBucket: 'protocol-app-6fb88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5Wylh3_XoEJitcx8U80T7TtH9Jx3A5E',
    appId: '1:268931083169:ios:e76d2e75f44a7e759579e0',
    messagingSenderId: '268931083169',
    projectId: 'protocol-app-6fb88',
    storageBucket: 'protocol-app-6fb88.firebasestorage.app',
    iosBundleId: 'com.example.protocolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5Wylh3_XoEJitcx8U80T7TtH9Jx3A5E',
    appId: '1:268931083169:ios:e76d2e75f44a7e759579e0',
    messagingSenderId: '268931083169',
    projectId: 'protocol-app-6fb88',
    storageBucket: 'protocol-app-6fb88.firebasestorage.app',
    iosBundleId: 'com.example.protocolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDES9L5keG2HvOqHGyKad-sngmtCSAXNUo',
    appId: '1:268931083169:web:6cc6af377f106ffc9579e0',
    messagingSenderId: '268931083169',
    projectId: 'protocol-app-6fb88',
    authDomain: 'protocol-app-6fb88.firebaseapp.com',
    storageBucket: 'protocol-app-6fb88.firebasestorage.app',
    measurementId: 'G-0QSVD1K0Z8',
  );
}
